[2024-03-12T14:14:32.724+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:14:32.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/indeed_scraper.py for tasks to queue
[2024-03-12T14:14:32.726+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:14:32.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:14:32.732+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:14:32.731+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/__pycache__/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:14:32.733+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:14:32.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/indeed_scraper.py took 0.026 seconds
[2024-03-12T14:15:03.054+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:15:03.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/indeed_scraper.py for tasks to queue
[2024-03-12T14:15:03.056+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:15:03.056+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:15:03.060+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:15:03.059+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/__pycache__/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:15:03.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:15:03.072+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/indeed_scraper.py took 0.021 seconds
[2024-03-12T14:15:33.395+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:15:33.396+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/indeed_scraper.py for tasks to queue
[2024-03-12T14:15:33.397+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:15:33.397+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:15:33.400+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:15:33.399+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/__pycache__/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:15:33.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:15:33.409+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/indeed_scraper.py took 0.015 seconds
[2024-03-12T14:16:03.791+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:16:03.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/indeed_scraper.py for tasks to queue
[2024-03-12T14:16:03.795+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:16:03.794+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:16:03.802+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:16:03.801+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/__pycache__/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:16:03.802+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:16:03.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/indeed_scraper.py took 0.033 seconds
[2024-03-12T14:16:34.226+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:16:34.227+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/indeed_scraper.py for tasks to queue
[2024-03-12T14:16:34.229+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:16:34.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:16:34.236+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:16:34.235+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/__pycache__/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:16:34.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:16:34.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/indeed_scraper.py took 0.032 seconds
[2024-03-12T14:17:04.640+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:17:04.641+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/indeed_scraper.py for tasks to queue
[2024-03-12T14:17:04.642+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:17:04.642+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:17:04.648+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:17:04.647+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/__pycache__/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:17:04.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:17:04.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/indeed_scraper.py took 0.028 seconds
[2024-03-12T14:17:35.043+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:17:35.043+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/__pycache__/indeed_scraper.py for tasks to queue
[2024-03-12T14:17:35.045+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:17:35.044+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:17:35.048+0000] {logging_mixin.py:188} INFO - [2024-03-12T14:17:35.048+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/__pycache__/indeed_scraper.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/indeed_scraper.py", line 1, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-03-12T14:17:35.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/indeed_scraper.py
[2024-03-12T14:17:35.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/__pycache__/indeed_scraper.py took 0.020 seconds
